Development (#250)
* remove unused variables
* fix badges
* user set

diff --git a/rootfs/etc/cont-init.d/20-set-app-defaults b/rootfs/etc/cont-init.d/20-set-app-defaults
--- a/rootfs/etc/cont-init.d/20-set-app-defaults
+++ b/rootfs/etc/cont-init.d/20-set-app-defaults
@@ -7,85 +7,64 @@
 #---------------------------------------------------------------------------------------------------------------------------
 # FUNCTIONS
 #---------------------------------------------------------------------------------------------------------------------------
-function _info  () { printf "\\r[ \\033[00;34mINFO\\033[0m ] %s\\n" "$@"; }
-function _warn  () { printf "\\r\\033[2K[ \\033[0;33mWARN\\033[0m ] %s\\n" "$@"; }
-function _error () { printf "\\r\\033[2K[ \\033[0;31mFAIL\\033[0m ] %s\\n" "$@"; }
-function _debug () { printf "\\r[ \\033[00;37mDBUG\\033[0m ] %s\\n" "$@"; }
+function _info() { printf "\\r[ \\033[00;34mINFO\\033[0m ] %s\\n" "$@"; }
+function _warn() { printf "\\r\\033[2K[ \\033[0;33mWARN\\033[0m ] %s\\n" "$@"; }
+function _error() { printf "\\r\\033[2K[ \\033[0;31mFAIL\\033[0m ] %s\\n" "$@"; }
+function _debug() { printf "\\r[ \\033[00;37mDBUG\\033[0m ] %s\\n" "$@"; }
 
 function _pre_reqs() {
-  _info "DSMR release: ${DSMR_VERSION}"
+  _info "DSMR Reader release: ${DSMR_VERSION}"
+  _info "DSMR Reader Docker release: ${DOCKER_TARGET_RELEASE}"
 
-  _info "Creating log directory..."
-  mkdir -p /var/log/supervisor/
+  _info "Ensure permissions..."
+  chown -R app:app /app
+  chown -R app:app /config
+  chown -R app:app /defaults
 
   _info "Setting architecture requirements..."
   _detect_architecture
 }
 
 function _detect_architecture() {
-    arch=$(uname -m)
-    # _info "uname -m output: ${arch}"
-    longbit=$(getconf LONG_BIT)
-    if [[ "$arch" == 'x86_64' ]]; then
-      if [[ "$longbit" = '32' ]]; then
-        arch="i386"
-        _info "X32 Architecture"
-      else
-        arch="amd64"
-        _info "X64 Architecture"
-      fi
-    fi
-    if [[ "$arch" == 'x86_32' ]]; then
+  arch=$(uname -m)
+  # _info "uname -m output: ${arch}"
+  longbit=$(getconf LONG_BIT)
+  if [[ "$arch" == 'x86_64' ]]; then
+    if [[ "$longbit" = '32' ]]; then
       arch="i386"
       _info "X32 Architecture"
-    fi
-    if [[ "$arch" == 'armv7l' ]]; then
-      arch="ARM"
-      _info "ARM Architecture"
-    fi
-    if [[ "$arch" == 'aarch64' ]]; then
-      arch="ARM64"
-      _info "ARM Architecture"
-    fi
-    if [ "$arch" == 'unknown' ]; then
-      #Assuming amd64, need to address certain distros uname giving "unknown"
+    else
       arch="amd64"
       _info "X64 Architecture"
     fi
+  fi
+  if [[ "$arch" == 'x86_32' ]]; then
+    arch="i386"
+    _info "X32 Architecture"
+  fi
+  if [[ "$arch" == 'armv7l' ]]; then
+    arch="ARM"
+    _info "ARM Architecture"
+  fi
+  if [[ "$arch" == 'aarch64' ]]; then
+    arch="ARM64"
+    _info "ARM Architecture"
+  fi
+  if [ "$arch" == 'unknown' ]; then
+    #Assuming amd64, need to address certain distros uname giving "unknown"
+    arch="amd64"
+    _info "X64 Architecture"
+  fi
 }
 
 function _dsmr_datalogger_mode() {
   if [[ "${DATALOGGER_MODE}" = standalone ]]; then
     _info "Configuring DSMR in standlone datalogger mode...."
-    export SD_AUTOSTART_DATALOGGER=true
-    export SD_AUTORESTART_DATALOGGER=false
-    export SD_AUTOSTART_REMOTE_DATALOGGER=false
-    export SD_AUTORESTART_REMOTE_DATALOGGER=false
-    export SD_AUTOSTART_BACKEND=true
-    export SD_AUTORESTART_BACKEND=false
-    export SD_AUTOSTART_WEBINTERFACE=true
-    export SD_AUTORESTART_WEBINTERFACE=false
   elif [[ "${DATALOGGER_MODE}" = sender ]]; then
     _info "Configuring DSMR in sender datalogger mode...."
-    export SD_AUTOSTART_DATALOGGER=false
-    export SD_AUTORESTART_DATALOGGER=false
-    export SD_AUTOSTART_REMOTE_DATALOGGER=true
-    export SD_AUTORESTART_REMOTE_DATALOGGER=false
-    export SD_AUTOSTART_BACKEND=false
-    export SD_AUTORESTART_BACKEND=false
-    export SD_AUTOSTART_WEBINTERFACE=false
-    export SD_AUTORESTART_WEBINTERFACE=false
     __dsmr_client_installation
   elif [[ "${DATALOGGER_MODE}" = receiver ]]; then
     _info "Configuring DSMR in receiver datalogger mode...."
-    export SD_AUTOSTART_DATALOGGER=false
-    export SD_AUTORESTART_DATALOGGER=false
-    export SD_AUTOSTART_REMOTE_DATALOGGER=false
-    export SD_AUTORESTART_REMOTE_DATALOGGER=false
-    export SD_AUTOSTART_BACKEND=true
-    export SD_AUTORESTART_BACKEND=false
-    export SD_AUTOSTART_WEBINTERFACE=true
-    export SD_AUTORESTART_WEBINTERFACE=false
   else
     _error "Invalid value of the DATALOGGER_MODE has been set. Exiting..."
     exit 1
@@ -94,10 +73,10 @@ function _dsmr_datalogger_mode() {
 
 function __dsmr_client_installation() {
   _info "Installing the DSMR remote datalogger client..."
-  touch /dsmr/.env
+  touch /app/.env
   if [[ -z "${DATALOGGER_API_HOSTS}" || -z "${DATALOGGER_API_KEYS}" || -z "${DATALOGGER_INPUT_METHOD}" ]]; then
-      _error "DATALOGGER_API_HOSTS and/or DATALOGGER_API_KEYS and/or DATALOGGER_INPUT_METHOD required values are not set. Exiting..."
-      exit 1
+    _error "DATALOGGER_API_HOSTS and/or DATALOGGER_API_KEYS and/or DATALOGGER_INPUT_METHOD required values are not set. Exiting..."
+    exit 1
   else
     if [[ "${DATALOGGER_INPUT_METHOD}" = ipv4 ]]; then
       _info "Using a network socket for the DSMR remote datalogger..."
@@ -106,7 +85,10 @@ function __dsmr_client_installation() {
         exit 1
       else
         _info "Adding DATALOGGER_NETWORK_HOST and DATALOGGER_NETWORK_PORT to the DSMR remote datalogger configuration..."
-        { echo DATALOGGER_NETWORK_HOST="${DATALOGGER_NETWORK_HOST}"; echo DATALOGGER_NETWORK_PORT="${DATALOGGER_NETWORK_PORT}"; } >> /dsmr/.env
+        {
+          echo DATALOGGER_NETWORK_HOST="${DATALOGGER_NETWORK_HOST}"
+          echo DATALOGGER_NETWORK_PORT="${DATALOGGER_NETWORK_PORT}"
+        } >>/app/.env
       fi
     elif [[ "${DATALOGGER_INPUT_METHOD}" = serial ]]; then
       _info "Using a serial connection for the DSMR remote datalogger..."
@@ -115,29 +97,36 @@ function __dsmr_client_installation() {
         exit 1
       else
         _info "Adding DATALOGGER_SERIAL_PORT and DATALOGGER_SERIAL_PORT to the DSMR remote datalogger configuration..."
-        { echo DATALOGGER_SERIAL_PORT="${DATALOGGER_SERIAL_PORT}"; echo DATALOGGER_SERIAL_PORT="${DATALOGGER_SERIAL_PORT}"; } >> /dsmr/.env
+        {
+          echo DATALOGGER_SERIAL_PORT="${DATALOGGER_SERIAL_PORT}"
+          echo DATALOGGER_SERIAL_PORT="${DATALOGGER_SERIAL_PORT}"
+        } >>/app/.env
       fi
     else
       _error "Incorrect configuration of the DATALOGGER_INPUT_METHOD value. Exiting..."
       exit 1
     fi
     _info "Adding DATALOGGER_API_HOSTS, DATALOGGER_API_KEYS and DATALOGGER_INPUT_METHOD to the DSMR remote datalogger configuration..."
-    { echo DATALOGGER_API_HOSTS="${DATALOGGER_API_HOSTS}"; echo DATALOGGER_API_KEYS="${DATALOGGER_API_KEYS}"; echo DATALOGGER_INPUT_METHOD="${DATALOGGER_INPUT_METHOD}"; } >> /dsmr/.env
+    {
+      echo DATALOGGER_API_HOSTS="${DATALOGGER_API_HOSTS}"
+      echo DATALOGGER_API_KEYS="${DATALOGGER_API_KEYS}"
+      echo DATALOGGER_INPUT_METHOD="${DATALOGGER_INPUT_METHOD}"
+    } >>/app/.env
   fi
 
   if [[ -n "${DATALOGGER_TIMEOUT}" ]]; then
     _info "Adding DATALOGGER_TIMEOUT to the DSMR remote datalogger configuration..."
-    echo DATALOGGER_TIMEOUT="${DATALOGGER_TIMEOUT}" >> /dsmr/.env
+    echo DATALOGGER_TIMEOUT="${DATALOGGER_TIMEOUT}" >>/app/.env
   fi
 
   if [[ -n "${DATALOGGER_SLEEP}" ]]; then
     _info "Adding DATALOGGER_SLEEP to the DSMR remote datalogger configuration..."
-    echo DATALOGGER_SLEEP="${DATALOGGER_SLEEP}" >> /dsmr/.env
+    echo DATALOGGER_SLEEP="${DATALOGGER_SLEEP}" >>/app/.env
   fi
 
   if [[ -n "${DATALOGGER_DEBUG_LOGGING}" ]]; then
     _info "Adding DATALOGGER_DEBUG_LOGGING to the DSMR remote datalogger configuration..."
-    echo DATALOGGER_DEBUG_LOGGING="${DATALOGGER_DEBUG_LOGGING}" >> /dsmr/.env
+    echo DATALOGGER_DEBUG_LOGGING="${DATALOGGER_DEBUG_LOGGING}" >>/app/.env
   fi
 }
 
@@ -164,7 +153,7 @@ function _check_db_availability() {
         fi
       else
         _info "Database connectivity successfully verified!"
-        if [[ "${VACUUM_DB_ON_STARTUP}" = true ]] ; then
+        if [[ "${VACUUM_DB_ON_STARTUP}" = true ]]; then
           _cleandb
         fi
         break
@@ -175,16 +164,16 @@ function _check_db_availability() {
 
 function _run_post_config() {
   _info "Running post configuration..."
-  /usr/local/bin/python3 /dsmr/manage.py migrate --noinput
-  /usr/local/bin/python3 /dsmr/manage.py collectstatic --noinput
-  /usr/local/bin/python3 /dsmr/manage.py dsmr_superuser
+  /usr/local/bin/python3 /app/manage.py migrate --noinput
+  /usr/local/bin/python3 /app/manage.py collectstatic --noinput
+  /usr/local/bin/python3 /app/manage.py dsmr_superuser
 }
 
 function _nginx_ssl_configuration() {
   _info "Checking for NGINX SSL configuration..."
   if [[ -n "${ENABLE_NGINX_SSL}" ]]; then
-    if [[ "${ENABLE_NGINX_SSL}" = true ]] ; then
-      if [[ ! -f "/etc/ssl/private/fullchain.pem" ]] && [[ ! -f "/etc/ssl/private/fullchain.pem" ]] ; then
+    if [[ "${ENABLE_NGINX_SSL}" = true ]]; then
+      if [[ ! -f "/etc/ssl/private/fullchain.pem" ]] && [[ ! -f "/etc/ssl/private/fullchain.pem" ]]; then
         _error "Make sure /etc/ssl/private/fullchain.pem and /etc/ssl/private/privkey.pem are mounted in the Docker container and exist!"
         exit 1
       else
@@ -193,7 +182,8 @@ function _nginx_ssl_configuration() {
       if grep -q "443" /etc/nginx/http.d/dsmr-webinterface.conf; then
         _info "SSL has already been enabled..."
       else
-        sed -i '/listen\s*80/r '<(cat <<- END_HEREDOC
+        sed -i '/listen\s*80/r '<(
+          cat <<-END_HEREDOC
         listen 443 ssl;
         ssl_certificate /etc/ssl/private/fullchain.pem;
         ssl_certificate_key /etc/ssl/private/privkey.pem;
@@ -215,7 +205,7 @@ END_HEREDOC
 function _generate_auth_configuration() {
   _info "Checking for HTTP AUTHENTICATION configuration..."
   if [[ -n "${ENABLE_HTTP_AUTH}" ]]; then
-    if [[ "${ENABLE_HTTP_AUTH}" = true ]] ; then
+    if [[ "${ENABLE_HTTP_AUTH}" = true ]]; then
       _info "ENABLE_HTTP_AUTH is enabled, let's secure this!"
       canWeContinue=true
       if [[ -z "${HTTP_AUTH_USERNAME}" ]]; then
@@ -226,13 +216,13 @@ function _generate_auth_configuration() {
         _warn "Please provide a HTTP_AUTH_PASSWORD"
         canWeContinue=false
       fi
-      if [[ "${canWeContinue}" = false ]] ; then
+      if [[ "${canWeContinue}" = false ]]; then
         _error "Cannot generate a valid .htpasswd file, please check above warnings."
         exit 1
       fi
       _info "Generating htpasswd..."
-	    HTTP_AUTH_CRYPT_PASSWORD=$(openssl passwd -apr1 "${HTTP_AUTH_PASSWORD}")
-    	printf "%s:%s\n" "${HTTP_AUTH_USERNAME}" "${HTTP_AUTH_CRYPT_PASSWORD}" > /etc/nginx/htpasswd
+      HTTP_AUTH_CRYPT_PASSWORD=$(openssl passwd -apr1 "${HTTP_AUTH_PASSWORD}")
+      printf "%s:%s\n" "${HTTP_AUTH_USERNAME}" "${HTTP_AUTH_CRYPT_PASSWORD}" >/etc/nginx/htpasswd
       _info "Done! Enabling the configuration in NGINX..."
       sed -i "s/##    auth_basic/    auth_basic/" /etc/nginx/http.d/dsmr-webinterface.conf
       if nginx -c /etc/nginx/nginx.conf -t 2>/dev/null; then
@@ -250,7 +240,7 @@ function _generate_auth_configuration() {
 function _iframe {
   if [[ "${ENABLE_IFRAME}" = true ]]; then
     _info "Enabling IFrame..."
-    sed -i "/^from dsmrreader.*/a X_FRAME_OPTIONS = 'ALLOWALL'" /dsmr/dsmrreader/settings.py
+    sed -i "/^from dsmrreader.*/a X_FRAME_OPTIONS = 'ALLOWALL'" /app/dsmrreader/settings.py
   fi
 }
 
