Development (#361)
* bugfix websocket timeout

diff --git a/rootfs/etc/s6-overlay/s6-rc.d/svc-nginx/run b/rootfs/etc/s6-overlay/s6-rc.d/svc-nginx/run
--- a/rootfs/etc/s6-overlay/s6-rc.d/svc-nginx/run
+++ b/rootfs/etc/s6-overlay/s6-rc.d/svc-nginx/run
@@ -2,10 +2,21 @@
 # shellcheck shell=bash
 
 if [[ "${DSMRREADER_OPERATION_MODE}" = standalone || "${DSMRREADER_OPERATION_MODE}" = api_server ]]; then
-    echo "Starting DSMR Reader - nginx..."
-    cd /app || exit
-    # s6-setuidgid app
-    /usr/sbin/nginx -g 'daemon off;'
+    for i in {1..10}; do
+        if [ -e "/tmp/gunicorn--dsmr_webinterface.socket" ]; then
+            echo "Starting DSMR Reader - nginx..."
+            sleep 2
+            cd /app || exit
+            /usr/sbin/nginx -g 'daemon off;'
+        else
+            sleep 1
+            printf "\\rTesting webservice socket connectivity: %s second(s) of 10 seconds..." "$i"
+            if [[ $i == 10 ]]; then
+                echo "Webinterface socket couldn't be verified! Please verify the webinterface log files. Exiting..."
+                exit 1
+            fi
+        fi
+    done
 else
     sleep infinity
 fi
